# Generated by Django 5.1.1 on 2024-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifftracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='utility',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
