# Generated by Django 5.1.1 on 2024-10-06 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifftracker', '0002_tariff_utility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('kwh', models.IntegerField()),
                ('escalator', models.FloatField()),
                ('selected_tariff', models.CharField(max_length=255)),
                ('cost_first_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openei_id', models.CharField(max_length=255)),
                ('tariff_name', models.CharField(max_length=255)),
                ('pricing_matrix', models.JSONField()),
                ('utility_name', models.CharField(max_length=255)),
                ('rate_structure', models.JSONField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarifftracker.project')),
            ],
        ),
    ]
